services:
  app:
    entrypoint:
      - sleep
      - infinity
    image: node:20.3.1-slim
    init: true
    ports:
      - '8100:8100'
      - '35729:35729'
    volumes:
      - .:/opt/ui
      - /opt/ui/node_modules
    command: apt-get update && apt-get install -y git bzip2 openssh-client && \
      npm install -g --unsafe-perm @ionic/cli@${IONIC_VERSION} && \
      ionic --version && \
      cd /tmp && \
      ionic start myNewProject blank --type=ionic-angular --capacitor && \
      cd myNewProject && \
      ionic build && \
      ionic capacitor build android --no-open && \
      rm -rf /tmp/myNewProject && \
      rm -rf /var/lib/apt/lists/* && apt-get clean
